version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=products_api
    volumes:
      - polls_pg_data:/bitnami/postgresql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/products_api
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run seed && npm run start:dev"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  polls_pg_data:
